variables:
  name: value

hooks:

  commit-msg:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'
    rules:
      - type: commit-message
        when: 1 == 1
        suffix: string
      - type: commit-message
        when: 1 == 1
        prefix: string
        suffix: string
      - type: commit-message
        when: 1 == 1
        prefix: string

  apply-patch-msg:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'

  fs-monitor-watchman:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'

  post-update:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'

  pre-apply-patch:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'

  pre-commit:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'
    rules:
      - type: suppress-commit-files
        when: 1 == 1
        globs: [glob1, glob2, glob3]
        remove-from-index: true
      - type: commit-message
        when: 1 == 1
        suffix: string
      - type: commit-message
        when: 1 == 1
        prefix: string
        suffix: string
      - type: commit-message
        when: 1 == 1
        prefix: string

    shell:
      windows: command4 arg1 arg2 arg3
      linux:
        script1:
          when: 1 == 1
          env:
            VAR1: VALUE1
            VAR2: VALUE2
          commands:
            - command2 arg1
            - command3 arg1 arg2
      darwin:
        script2: command1 arg1 arg2
    add-to-index:
      - '*.txt'
      - go.sum]
      - glob: package.json
        required: false
    suppress-commit-files:
      globs: [glob1, glob2, glob3]
      remove-from-index: true

  pre-push:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'

  pre-rebase:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'

  pre-receive:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'

  prepare-commit-msg:
    variables:
      name: value
    extract-variables:
      - variable: BranchName
        expression: '^refs/heads/(?P<IssueNumber>.*)$'

output:
  level: None
