variables:
  name: value

hooks:

  commit-msg:
    variables:
      from-branch: regexp
      from-last-tag: regexp

    rules:
      - type: commit-suffix
        when: 1 == 1
        suffix: string

      - type: commit-prefix
        when: 1 == 1
        prefix: string
        suffix: string

      - type: commit-regexp
        when: 1 == 1
        prefix: string

    not-empty: false
    commit-regexp: regexp
    commit-prefix: string
    commit-suffix: string
    static-message: string

  apply-patch-msg: null

  fs-monitor-watchman: null

  post-update: null

  pre-apply-patch: null

  pre-commit:
    variables:
      from-branch: regexp
      from-last-tag: regexp

    rules:

      - type: suppress-commit-files
        when: 1 == 1
        globs: [glob1, glob2, glob3]
        remove-from-index: true

      - type: commit-suffix
        when: 1 == 1
        suffix: string

      - type: commit-prefix
        when: 1 == 1
        prefix: string
        suffix: string

      - type: commit-regexp
        when: 1 == 1
        prefix: string

    shell:
      windows: command4 arg1 arg2 arg3
      linux:
        script1:
          when: 1 == 1
          env:
            VAR1: VALUE1
            VAR2: VALUE2
          commands:
            - command2 arg1
            - command3 arg1 arg2
      darwin:
        script2: command1 arg1 arg2
    add-to-index:
      - '*.txt'
      - go.sum]
      - glob: package.json
        required: false
    suppress-commit-files:
      globs: [glob1, glob2, glob3]
      remove-from-index: true

  pre-push:
    variables:
      from-branch: regexp
      from-last-tag: regexp
    shell:
      script1:
        - command1
        - command2
      script2:
        - command3
        - command4

  pre-rebase: null

  pre-receive: null

  prepare-commit-msg:
    variables:
      from-branch: regexp
    message: string
    shell:
      demo: 'ls'

output:
  level: None
