run:
  skip-dirs:
    - mocks
    - assets
  allow-parallel-runners: true
linters:
  enable:
    - gosec
    - unconvert
    - nlreturn
    - nestif
    - gomnd
    - stylecheck
    - gocyclo
    - maligned
    - dupl
    - misspell
    - unparam
    - whitespace
    - godox
    - golint
    - interfacer
    - goconst
    - asciicheck
    - lll
    - gocritic
    - vet
