builds:
  - goos:
      - linux
      - windows
      - darwin
    flags:
      - -tags=release
      - -v
    ldflags:
      - -s -w -X fisherman/constants.Version={{.Version}}

archives:
  - replacements:
      linux: Linux
      windows: Windows
      386: x86
      amd64: amd64
      darwin: MacOS
    format: zip

source:
  enabled: false

changelog:
  skip: true
