# https://taskfile.dev

version: '3'

vars:
  GIT_COMMIT:
    sh: git log -n 1 --format=%h

tasks:
  build:
    desc: Build the go binary in developer mode.
    cmds:
      - go build -v

  build:ci:
    desc: '[For CI] Build the go binary in production mode (NOT REALISE)'
    cmds:
      - go build -v -ldflags="-s -w -X fisherman/constants.Version=dev-{{ .GIT_COMMIT | upper }}"

  test:
    desc: Run all tests
    cmds:
      - go test -cover -v ./...

  test:ci:
    desc: '[For CI] Run all tests with coverage and race detection'
    cmds:
      - go test -race -cover -coverprofile='coverage.xml' -covermode=atomic -v ./...

  lint:
    desc: Lint all code
    cmds:
      - golangci-lint run ./...

  generate:
    desc: Generates mocks
    cmds:
     - go generate -n ./...
