name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build, Lint and Test
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.31
        
    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v ./main.go

    - name: Test
      run: go test -v -cover ./...
